  version: '3.8'

  services:
    db:
      image: postgres:14
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1111
        POSTGRES_DB: postgres

    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: app:latest
      depends_on:
        - db
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 1111

